error: redundant closure
  --> $DIR/eta.rs:28:27
   |
LL |     let a = Some(1u8).map(|a| foo(a));
   |                           ^^^^^^^^^^ help: replace the closure with the function itself: `foo`
   |
   = note: `-D clippy::redundant-closure` implied by `-D warnings`

error: redundant closure
  --> $DIR/eta.rs:32:40
   |
LL |     let _: Option<Vec<u8>> = true.then(|| vec![]); // special case vec!
   |                                        ^^^^^^^^^ help: replace the closure with `Vec::new`: `std::vec::Vec::new`

error: redundant closure
  --> $DIR/eta.rs:33:35
   |
LL |     let d = Some(1u8).map(|a| foo((|b| foo2(b))(a))); //is adjusted?
   |                                   ^^^^^^^^^^^^^ help: replace the closure with the function itself: `foo2`

error: redundant closure
  --> $DIR/eta.rs:34:26
   |
LL |     all(&[1, 2, 3], &&2, |x, y| below(x, y)); //is adjusted
   |                          ^^^^^^^^^^^^^^^^^^ help: replace the closure with the function itself: `below`

error: redundant closure
  --> $DIR/eta.rs:41:27
   |
LL |     let e = Some(1u8).map(|a| generic(a));
   |                           ^^^^^^^^^^^^^^ help: replace the closure with the function itself: `generic`

error: redundant closure
  --> $DIR/eta.rs:87:51
   |
LL |     let e = Some(TestStruct { some_ref: &i }).map(|a| a.foo());
   |                                                   ^^^^^^^^^^^ help: replace the closure with the method itself: `TestStruct::foo`
   |
   = note: `-D clippy::redundant-closure-for-method-calls` implied by `-D warnings`

error: redundant closure
  --> $DIR/eta.rs:88:51
   |
LL |     let e = Some(TestStruct { some_ref: &i }).map(|a| a.trait_foo());
   |                                                   ^^^^^^^^^^^^^^^^^ help: replace the closure with the method itself: `TestTrait::trait_foo`

error: redundant closure
  --> $DIR/eta.rs:90:42
   |
LL |     let e = Some(&mut vec![1, 2, 3]).map(|v| v.clear());
   |                                          ^^^^^^^^^^^^^ help: replace the closure with the method itself: `std::vec::Vec::clear`

error: redundant closure
  --> $DIR/eta.rs:94:29
   |
LL |     let e = Some("str").map(|s| s.to_string());
   |                             ^^^^^^^^^^^^^^^^^ help: replace the closure with the method itself: `std::string::ToString::to_string`

error: redundant closure
  --> $DIR/eta.rs:95:27
   |
LL |     let e = Some('a').map(|s| s.to_uppercase());
   |                           ^^^^^^^^^^^^^^^^^^^^ help: replace the closure with the method itself: `char::to_uppercase`

error: redundant closure
  --> $DIR/eta.rs:97:65
   |
LL |     let e: std::vec::Vec<char> = vec!['a', 'b', 'c'].iter().map(|c| c.to_ascii_uppercase()).collect();
   |                                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^ help: replace the closure with the method itself: `char::to_ascii_uppercase`

thread 'rustc' panicked at 'index out of bounds: the len is 0 but the index is 0', clippy_lints/src/path_from_format.rs:39:41
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust-clippy/issues/new

note: Clippy version: clippy 0.1.62 (01d75b195 2022-05-13)

query stack during panic:
#0 [analysis] running analysis passes on this crate
end of query stack
error: aborting due to 11 previous errors

